name: Deploy to ECR and ECS

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up environment variables
        run: |
          echo "TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
          echo "CLIENT_ID=${{ secrets.DISCORD_CLIENTID }}" >> .env
          echo "DB_URI=${{ secrets.MONGODB_URI }}" >> .env

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition vintedbot --query taskDefinition > task-definition.json

      - name: Build and push Docker image
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-region: us-west-2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/vintedbotapp:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          cluster: vintedbot_prod
          service: vintedbot
          container-name: vintedbot
