name: Deploy to ACR

on:
  workflow_dispatch:
  push:
    tags:
      - '*'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: vintedbot.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Set up environment variables
        run: |
          echo "TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
          echo "CLIENT_ID=${{ secrets.DISCORD_CLIENTID }}" >> .env
          echo "DB_URI=${{ secrets.MONGODB_URI }}" >> .env
      
      - name: Build and tag Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: vintedbot.azurecr.io/vintedbotapp:${{ github.ref_name }}
      
      - name: Push Docker image to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vintedbot.azurecr.io/vintedbotapp:${{ github.ref_name }}
          build-args: |
            TOKEN=${{ secrets.DISCORD_TOKEN }}
            CLIENT_ID=${{ secrets.DISCORD_CLIENTID }}
            DB_URI=${{ secrets.MONGODB_URI }}
      
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: vintedbotapp
          images: vintedbot.azurecr.io/vintedbotapp:${{ github.ref_name }}
